<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED>

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,Step*,DIter*,Action*,Summary?,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,NodeArgs) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="9.0" os="Windows XP" host="LHX00CNU7420CWT"><DocLocation><![CDATA[C:\STBK_Framework\QTP Scripts\Driver Script]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Driver Script]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="5" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Driver Script]]></AName>
<Action rID="T5">
<AName><![CDATA[Main Script]]></AName>
<Step rID="T6" >
<Obj plainTxt="False" ><![CDATA[TeWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[TeWindow]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:10]]></Time>
<Step rID="T7" >
<Obj plainTxt="False" ><![CDATA[TeScreen]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:10]]></Time>
<Step rID="T8" >
<Obj plainTxt="False" ><![CDATA[TeScreen]]></Obj>
<Details plainTxt="False" ><![CDATA[Object does not exist]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:10]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="14" nType="TeScreen" >
<Disp><![CDATA[TeScreen]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" >
<Disp><![CDATA[TeScreen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9" >
<Obj plainTxt="False" ><![CDATA[Menu.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:16]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="18" >
<Disp><![CDATA[Menu.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10" >
<Obj plainTxt="False" ><![CDATA[TeScreen]]></Obj>
<Details plainTxt="False" ><![CDATA[TeScreen]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:32]]></Time>
<Step rID="T11" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:32]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="21" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:32]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="22" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:33]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="23" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14" >
<Obj plainTxt="False" ><![CDATA[Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[Sync]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:33]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="24" >
<Disp><![CDATA[Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15" >
<Obj plainTxt="False" ><![CDATA[SetText 3,1,"CICTBF01"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetText 3,1,"CICTBF01"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:34]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="27" >
<Disp><![CDATA[SetText 3,1,"CICTBF01"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ENTER"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ENTER"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:34]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="29" >
<Disp><![CDATA[SendKey "TE_ENTER"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17" >
<Obj plainTxt="False" ><![CDATA[TeScreen]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:35]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="30" nType="TeScreen" >
<Disp><![CDATA[TeScreen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18" >
<Obj plainTxt="False" ><![CDATA[TeScreen]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:35]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="31" nType="TeScreen" >
<Disp><![CDATA[TeScreen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_CLEAR"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_CLEAR"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:35]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="33" >
<Disp><![CDATA[SendKey "TE_CLEAR"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:36]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="34" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:36]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="35" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:36]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="36" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23" >
<Obj plainTxt="False" ><![CDATA[Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[Sync]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:36]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="37" >
<Disp><![CDATA[Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24" >
<Obj plainTxt="False" ><![CDATA[SetText 1,2,"TOFU"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetText 1,2,"TOFU"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:38]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="40" >
<Disp><![CDATA[SetText 1,2,"TOFU"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ENTER"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ENTER"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:38]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="42" >
<Disp><![CDATA[SendKey "TE_ENTER"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26" >
<Obj plainTxt="False" ><![CDATA[TeScreen]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:38]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="43" nType="TeScreen" >
<Disp><![CDATA[TeScreen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27" >
<Obj plainTxt="False" ><![CDATA[TeScreen]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:39]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="44" nType="TeScreen" >
<Disp><![CDATA[TeScreen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:39]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="45" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:39]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="46" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:39]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="47" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31" >
<Obj plainTxt="False" ><![CDATA[Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[Sync]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:39]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="48" >
<Disp><![CDATA[Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32" >
<Obj plainTxt="False" ><![CDATA[SetText 22,6,"999093365"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetText 22,6,"999093365"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:41]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="51" >
<Disp><![CDATA[SetText 22,6,"999093365"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:41]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="52" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34" >
<Obj plainTxt="False" ><![CDATA[Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[Sync]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:41]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="53" >
<Disp><![CDATA[Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35" >
<Obj plainTxt="False" ><![CDATA[SetText 22,20,"test01"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetText 22,20,"test01"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:43]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="56" >
<Disp><![CDATA[SetText 22,20,"test01"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ENTER"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ENTER"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:43]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="58" >
<Disp><![CDATA[SendKey "TE_ENTER"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37" >
<Obj plainTxt="False" ><![CDATA[TeScreen]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:43]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="59" nType="TeScreen" >
<Disp><![CDATA[TeScreen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38" >
<Obj plainTxt="False" ><![CDATA[TeScreen]]></Obj>
<Details plainTxt="False" ><![CDATA[Object exists]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:44]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="60" nType="TeScreen" >
<Disp><![CDATA[TeScreen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_CLEAR"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_CLEAR"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:45]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="62" >
<Disp><![CDATA[SendKey "TE_CLEAR"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_HOME"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_HOME"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:45]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="64" >
<Disp><![CDATA[SendKey "TE_HOME"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:45]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="66" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:45]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="68" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:45]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="70" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:46]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="72" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:46]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="74" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:46]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="76" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:46]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="78" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:46]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="80" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:46]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="82" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:47]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="84" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:47]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="86" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:47]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="88" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:47]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="90" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:47]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="92" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:47]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="94" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:47]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="96" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:47]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="98" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:48]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="100" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:48]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="102" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:48]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="104" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:48]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="106" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:48]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="108" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:48]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="110" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:48]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="112" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:48]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="114" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:49]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="116" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:49]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="118" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:49]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="120" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_ERASE_EOF"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:49]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="122" >
<Disp><![CDATA[SendKey "TE_ERASE_EOF"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70" >
<Obj plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Obj>
<Details plainTxt="False" ><![CDATA[SendKey "TE_TAB"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:49]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="124" >
<Disp><![CDATA[SendKey "TE_TAB"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:49]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="125" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:49]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="126" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:49]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="127" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74" >
<Obj plainTxt="False" ><![CDATA[Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[Sync]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:49]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="128" >
<Disp><![CDATA[Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75" >
<Obj plainTxt="False" ><![CDATA[SetText 4,19,"U"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetText 4,19,"U"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:51]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="131" >
<Disp><![CDATA[SetText 4,19,"U"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:51]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="132" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77" >
<Obj plainTxt="False" ><![CDATA[Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[Sync]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:51]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="133" >
<Disp><![CDATA[Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78" >
<Obj plainTxt="False" ><![CDATA[SetText 4,35,"0929215070"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetText 4,35,"0929215070"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:53]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="136" >
<Disp><![CDATA[SetText 4,35,"0929215070"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T79" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:53]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="137" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T80" >
<Obj plainTxt="False" ><![CDATA[Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[Sync]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:53]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="138" >
<Disp><![CDATA[Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T81" >
<Obj plainTxt="False" ><![CDATA[SetText 4,57,"0929215070"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetText 4,57,"0929215070"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:54]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="141" >
<Disp><![CDATA[SetText 4,57,"0929215070"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T82" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:55]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="142" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T83" >
<Obj plainTxt="False" ><![CDATA[Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[Sync]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:55]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="143" >
<Disp><![CDATA[Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T84" >
<Obj plainTxt="False" ><![CDATA[SetText 4,73,"101909"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetText 4,73,"101909"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:56]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="146" >
<Disp><![CDATA[SetText 4,73,"101909"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T85" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:56]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="147" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T86" >
<Obj plainTxt="False" ><![CDATA[Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[Sync]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:56]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="148" >
<Disp><![CDATA[Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T87" >
<Obj plainTxt="False" ><![CDATA[SetText 5,29,"828"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetText 5,29,"828"]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:58]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="151" >
<Disp><![CDATA[SetText 5,29,"828"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T88" >
<Obj plainTxt="False" ><![CDATA[WaitString "",0,0,0,0,60000,0]]></Obj>
<Details plainTxt="False" ><![CDATA[The specified string was found at these coordinates in 0 seconds.]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:58]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="152" nType="TeScreen" >
<Disp><![CDATA[WaitString "",0,0,0,0,60000,0]]></Disp>
</NodeArgs>
</Step>
<Step rID="T89" >
<Obj plainTxt="False" ><![CDATA[Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[Sync]]></Details>
<Time><![CDATA[3/31/2009 - 19:28:58]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="153" >
<Disp><![CDATA[Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T90" >
<Obj plainTxt="False" ><![CDATA[SetText 9,10,"15070"]]></Obj>
<Details plainTxt="False" ><![CDATA[SetText 9,10,"15070"]]></Details>
<Time><![CDATA[3/31/2009 - 19:29:00]]></Time>